markdown:	redcarpet
highlighter: 	rouge
encoding: 	utf-8
permalink: 	/:title
url: 		http://assist.hilbri.ch
baseurl:
destination:	../Online

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
